### Import Library

In [1]:
#202131037_Anugrah AK.
import cv2 as cv

In [2]:
#20231037_Anugrah AK.
import numpy as np

### Membaca Gambar

In [3]:
#202131037_Anugrah AK.
medical = cv.imread('citra_medis.jpg')

In [4]:
#202131037_Anugrah AK.
cv.imshow("citra medis awal",medical)
cv.waitKey(0)
cv.destroyAllWindows()

### Dimensi Gambar dan Tipe Data

In [5]:
#202131037_Anugrah AK.
print(medical.shape)
print(medical.dtype)

(128, 128, 3)
uint8


### Membagi Gambar RGB

In [6]:
#202131037_Anugrah AK.
b = medical[:,:,0]
g = medical[:,:,0]
r = medical[:,:,0]

### Mengkonversi Gambar RGB ke Grayscale

In [7]:
#202131037_Anugrah AK.
panjang = len(medical)
lebar = len(medical)

medical_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        medical_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j]
        
medical_gray = medical_gray.astype(np.uint8)

In [8]:
#202131037_Anugrah AK.
cv.imshow('Medical Gray', medical_gray)
cv.waitKey(0)
cv.destroyAllWindows()

In [9]:
#202131037_Anugrah AK.
print(medical_gray)

[[  3   3   3 ... 142 135 133]
 [  3   3   3 ... 142 132 127]
 [  3   3   3 ... 141 132 127]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


### Mengkonversi Grayscale ke Biner

In [10]:
#202131037_Anugrah AK.
panjang=len(medical) 
lebar=len(medical[0])

threshold=255

medical_biner=np.zeros((panjang,lebar)) 
for i in range (panjang):
    for j in range (lebar):
        if medical_gray[i,j]>=threshold:
            medical_biner[i,j]=0 
        else: 
                medical_biner[i,j]=1

In [11]:
#202131037_Anugrah AK.
cv.imshow('Medical Biner', medical_gray)
cv.waitKey(0)
cv.destroyAllWindows()

### Cetak Piksel pada indeks tertentu

In [12]:
#202131037_Anugrah AK.
print(medical_gray[50,50])

143


In [13]:
#202131037_Anugrah AK.
print(medical_biner[50,50])

1.0
